### ISSUE TITLE
Make function names more descriptive

### ISSUE THREAD

**Issue by wvictor14** [Yifan-Yin/DMR-Project#12]
I find that the function names are confusing. After not working on the app for some time, it always takes me awhile to remember what each function does. What I do like about them now is that there is at least some consistency in them (e.g. most are prefixed by `cpg_`). 

**It would be useful for us in the future, if the function names were a bit more descriptive.**

In general, function names should be verbs, and object names should be nouns. [Here's](https://style.tidyverse.org/functions.html#naming) a good resource on function/object naming best practices.

Here's an example of what I mean:

1. `fn_cpg()`
`fn_cpg()` takes in a `gene_name` (a search string), and returns a character vector of associated cpgs

I'm not sure what the `fn` stands for, but maybe it would be better named: `return_cpg_ids` or `find_cpg_ids`

2. `cpg_info_total()`
 `cpg_info_total()` seems to be only used for generating the data.table output. Given cpg ids or gene symbol, it returns the relevant subset of the annotation.

Therefore, maybe `make_datatable_output()` or `subset_annotation()` might be better names.

This issue is also relevant in the internal object names that are being used. e.g. `cpg`, `cpg_info` - these are OK, but IMO can be better. (e.g. `cpg` => `annotation_subset`).

Sidenote - looking at the  `cpg_info_total()` function, I realized that there is some unnecessarily defined functions. `cpg_info_gene` and `cpg_info` are only used within the function `cpg_info_total`, AND their code are only 1-2 lines each. It is much less confusing to just copy their code directly into `cpg_info_total` and remove their definitions entirely. **I did this in c57d401a482c540ca97be106b389b36732d4bd06**, but I wanted to explain because I think it's very relevant with respect to keeping code easy to understand, which is the underlying issue tackled here.

I think it would be a good exercise for you @Yifan-Yin  to attempt to try renaming some of these functions. Let me know if you want any help / ideas, I'd be happy to contribute.

**Comment by Yifan-Yin** [comment]
Yes, I also find the some of the function names are not appropriate. I will rename the functions to make it more clear.

**Comment by Yifan-Yin** [comment]
Yes, I also find the some of the function names are not appropriate. The naming standard is based on what I learnt from a Python course. fn_cpg stands for find_cpg.  I will rename the functions to make it more clear.

**Comment by wvictor14** [comment]
This is an on-going thing. Will close this
