### ISSUE TITLE
UI organization

### ISSUE THREAD

**Issue by wvictor14** [Yifan-Yin/DMR-Project#13]
Hi Yifan,

I started exploring some of your recent changes. They are really great, thanks for doing this.

The UI organization could be a bit better. Some aspects are a bit confusing. 

I suggest making these changings:

-  [x] 1. The DMC columns "First_trophoblast_cs, Third_stromal_cs etc." should not be shown in the annotation table.
- [x] 2. The input options "# CpGs to plot" and "Start - End CpG" are redundant. I think we should keep "Start/end" and remove "# of CpGs to plot".
- [x] 3. "Start / End CpGs" can we use a [slider](https://shiny.rstudio.com/articles/sliders.html) for this input?
- [x] 4. Right now it is difficult to see how the different inputs correspond to the different outputs. For example, the "If a specific gene is selected, then you can also display specific associated-CpGs" input is not obvious that it will correspond to boxplots showing up at the very bottom. "Cell types to show" is also not obvious that it only affects the main plot.

I think 4. can be fixed by adding some headings and moving around the order of the inputs. I will try this maybe this afternoon.

**Comment by Yifan-Yin** [comment]
Hi Victor,

Glad to hear that you like the changes. 

1. Do you mean remove the DMC columns permanently?  Or these colums are not shown as default, and users can show them when they select from the checkbox.
2. Yeah, I see. I will modify the code to remove the input of # of CpGs.
3. Looks good. It is more clear than numeric input. I will switch it into a slider.
4. I saw your updated code for the UI reorganization. However, there are some issues related to this change. 

(1) The tabset 'Individual CpG boxplots' only respond when given a gene input (cpgs in the search box are those associated with the input gene). I can modify the code to show the associated cpgs depends on whether it is a gene input, cpg inputs or a region input.

![image](https://user-images.githubusercontent.com/52260541/71133346-1abfeb00-21af-11ea-8fdd-d025b4ae1604.png)

(2)If we separate the datatable and boxplots on different tabsets, it might be impossible to click a cpg from the datatable to show the individual boxplot.

**Comment by wvictor14** [comment]
1. Yes, those columns are only going to be used for the "track" in the plot, but in my opinion should not be visible to the user
4.1 Yes, this is desired behaviour and it is OK as long as somewhere there is some description that makes this clear. 
4.2 This is true... Maybe combining the `CpG Annotation` and `Individual CpG Boxplots` would make sense? 

In the long term, I am thinking about creating another type of plot / view. It will be called something like "Genome Browser View" and the current "Browser" name will be changed to "Condensed Browser View". Genome Browser View will basically show the positional information of the cpgs, and will have gene transcript models as well. It will look something like `ggbio`'s plots:

![image](https://user-images.githubusercontent.com/22013187/71193611-3bd01c80-223f-11ea-9830-7c1761283c99.png)

But I will build the plot function from scratch since I find `ggbio` is too restrictive (even though it is built on `ggplot`)

I will probably start doing that during the break and hopefully finish by the end of next week but it depends on how busy I am during the holidays. Hope you have some time to enjoy yourself over these holidays, don't worry too much about work!

**Comment by Yifan-Yin** [comment]
Hi Victor,

I am interested in the ggbio plot you mentioned.  Don't worry about my time. I am always willing to help!

**Comment by wvictor14** [comment]
If you want to give it an attempt I'd be happy let you try first and I can give you a couple of tips to start off. The only thing right now is that this requires using detailed transcript information which I haven't had the time yet to download/process.

**Comment by wvictor14** [comment]
I've created this type a plot and am starting to look on how to implement it into the app. I'm thinking of displaying it in another tab.
