### ISSUE TITLE
plot refreshes everytime text is deleted from "gene input" box

### ISSUE THREAD

**Issue by wvictor14** [Yifan-Yin/DMR-Project#15]
An annoying bug where erasing the gene name from the "gene input" box causes the plot to refresh and display a bunch of random cpgs. 

Has something to do with the way the reactive values / observevent is set up

Ideally the plot refreshes only when the "submit" button is pressed.

**Comment by wvictor14** [comment]
I think this also applies to the region input tab too

**Comment by Yifan-Yin** [comment]
I see. I think I know how to do to solve the bug.

**Comment by Yifan-Yin** [comment]
I used reactive values as function inputs. Now the plot updates only when the 'submit' button is pressed.
