### ISSUE TITLE
Add a "select region" option

### ISSUE THREAD

**Issue by wvictor14** [Yifan-Yin/DMR-Project#5]
It might also be useful to be able to specify a specific region to visualize cpgs in.

something like:

Chr: 
Start:
End:

And then the default would be to take the first 20-30 CpGs to display.

**Comment by Yifan-Yin** [comment]
There are two options to add the Select Region funtion.
1.  One is put all of the search boxes in the same page. This might be a litte bit messy
![image](https://user-images.githubusercontent.com/52260541/68631293-27aa3a00-049f-11ea-8db7-5ace3336b1ac.png)

2. Another one is put the 'Region Selction' options in a new page by adding a tabset.
![image](https://user-images.githubusercontent.com/52260541/68631226-e1ed7180-049e-11ea-8ca0-347db40c0d59.png)
![image](https://user-images.githubusercontent.com/52260541/68631254-00ec0380-049f-11ea-8088-9a8aec729458.png)

**Comment by wvictor14** [comment]
Yeah, I agree - option 1 is messy.

I like option 2. In fact, could we separate gene and cpg into two tabs as well? (Making gene the default tab to show, because most people will come to the app with specific genes in mind).

**Comment by Yifan-Yin** [comment]
Hi Victor,

The 'region selection' option has been added. I am thinking how many cpgs within the selected region should be displayed. Maybe we can show all of them in the datatable, and show parts of them in the plot based on the number that users select (like how we did given a gene input).

**Comment by wvictor14** [comment]
Yes agree, all should be displayed in the datatable and only plot the selected ones - sounds good
