### ISSUE TITLE
Separate out transcripts plot on it's own

### ISSUE THREAD

**Issue by wvictor14** [Yifan-Yin/DMR-Project#6]
There's an issue with genes that have a lot of transcripts. The methylation plots basically get really squished and it is difficult to see anything. This is in part because I have this auto-adjust function at the end `ggarrange` call that's based on the number of transcripts. 

I think this could be fixed if we 

* separate out the transcripts plot (p3) and give it it's own plotOutput call after p1 + p2
* Fix the heights of p1 + p2

I'll post an example of the problem tomorrow

**Comment by wvictor14** [comment]
Here's an example of what I'm talking about. 

![image](https://user-images.githubusercontent.com/22013187/68412577-4f1ca200-0141-11ea-9016-804256ad822a.png)

I'm not sure how many genes have as many transcripts as BRCA1 (not many, probably).

**Comment by wvictor14** [comment]
@Yifan-Yin Can you give this one an attempt? I think you'll be able to do it faster/better than me

**Comment by Yifan-Yin** [comment]
> @Yifan-Yin Can you give this one an attempt? I think you'll be able to do it faster/better than me

Sounds good! I will figure it out by this weekend.

**Comment by wvictor14** [comment]
Thanks! 

Another solution might be to dynamically adjust the total plot height in the `plotOutput` call, based on the number of transcripts.

**Comment by Yifan-Yin** [comment]
The plot height will dynamically change depends on the number of transcripts for selceted gene. The hight will increase to 900 pixels when the number of transcipts is more than 20, otherwise it will be 800 pixels.

**Comment by wvictor14** [comment]
Cool! Can you post a picture of what it looks like now for BRCA1?

**Comment by Yifan-Yin** [comment]
This is a screenshot when the plot height is 900 pixels.
![image](https://user-images.githubusercontent.com/52260541/68533529-c76c9a00-02de-11ea-809c-cc1df588ba34.png)

This one is 1300 pixels.
![V XVR~66A2{N RP2 AL1FP2](https://user-images.githubusercontent.com/52260541/68533506-8aa0a300-02de-11ea-9f6f-dfaaa2c1bff7.png)

**Comment by wvictor14** [comment]
I think this is a good enough solution for now, but the aspect ratio is a bit messed up. I think the relative heights argument in the last `ggarrange` needs a bit of playing around with so that the function plays nice with many-transcript-genes and few-transcript-genes.

The problem with this type of solution though is that it is very time-consuming to go in and find the "right" settings (e.g. height of the output, relative heights of each plot, etc.). In retrospect, this was a result of a bad design decision on my part. Hopefully, at some point I will have enough time to give this a bit more attention. 

Consider this solved for now, but leave this issue open so I can return to this later. Thanks!
