### ISSUE TITLE
Genes with large number of cpgs are difficult to read

### ISSUE THREAD

**Issue by wvictor14** [Yifan-Yin/DMR-Project#7]
Genes with greater than 100 CpGs are difficult to read:

RBFOX3 has 250 CpGs:

![image](https://user-images.githubusercontent.com/22013187/69893505-092da680-12c7-11ea-959e-91639e81894d.png)

There should be an option to allow users to select how many CpGs to show at a time. Then, they can pick which set of CpGs to view (first 50, 51-100, 101-150, etc.).

My suggested solution would be to put take the user input as an argument into a `dplyr::slice` call after `betas_gene` is generated ([line 188](    https://github.com/Yifan-Yin/DMR-Project/blob/72d0e9468c4ce2f9db268a4ef5ca4153c4fb848e/DMC%20visualization.Rmd#L188)).

**Comment by Yifan-Yin** [comment]
The option to select the number of cpgs to plot and which set of cpgs to plot has been added.

**Comment by wvictor14** [comment]
Addressed in #5
