### ISSUE TITLE
Highlight certain cell types in the plots

### ISSUE THREAD

**Issue by wvictor14** [Yifan-Yin/DMR-Project#8]
Sometimes it is difficult to see what the methylation is for a particular cell type that is covered up by another. 

Add an option to allow users to select which cell types to show, and set the alpha of all others to 0 or something close to 0.

**Comment by Yifan-Yin** [comment]
Hi Victor,

The idea to address this issue is to add a checkbox (users can select the tissue types to plot) (https://github.com/Yifan-Yin/DMR-Project/blob/5ed296259862445d9bf71c9ddfc8b65c3daec6b2/shiny_DMR.Rmd#L125) in the shinyapp, and take it as an input in the plot function (annoPlot_with_tracks) so that certain cell types can be filtered.  However, something went wrong when I used dplyr::filter().  I applied the filter function to betas_gene (https://github.com/Yifan-Yin/DMR-Project/blob/5ed296259862445d9bf71c9ddfc8b65c3daec6b2/Tissue_Fliter_Plot.Rmd#L138).
Betas_gene was not taking all of the matched results. It was only taking 1/5 of the total samples no matter how many cell types were selected. I was not able find the solution, and I would appreciate it if you can help me out.

**Comment by wvictor14** [comment]
Hi Yifan,

I pulled your code and it seems to be working fine. Could you check again and if you're still experiencing unexpected results then copy + paste your code + output here?

```
> test_function(gene_name = 'DNMT1', Tissue_type = 'Endothelial cs') %>% 
+     pull(Tissue) %>%
+     table()
.
Endothelial cs 
            98 
```

```
 test_function(gene_name = 'DNMT1', Tissue_type = 'Hofbauer cs') %>% 
+     pull(Tissue) %>%
+     table()
.
Hofbauer cs 
         98 
```

```
test_function(gene_name = 'TET1', Tissue_type = 'Hofbauer cs') %>% 
+     pull(Tissue) %>%
+     table()
.
Hofbauer cs 
         82 
```

**Comment by Yifan-Yin** [comment]
Hi Victor

It works fine only when there is one tissue type input. When there are more than one tissue types, the result is not correct.

`> test_function(gene_name = 'TET1', Tissue_type = c('Endothelial cs', 'Hofbauer cs')) %>%  
+   pull(Tissue) %>% 
+   table()
.
Endothelial cs    Hofbauer cs 
            41             41 `

`> test_function(gene_name = 'TET1', Tissue_type = c('Endothelial cs', 'Villi','Hofbauer cs')) %>%  
+   pull(Tissue) %>% 
+   table()
longer object length is not a multiple of shorter object length.
Endothelial cs    Hofbauer cs          Villi 
            27             27             27 `

**Comment by wvictor14** [comment]
Ah I see.

You must use `%in%` instead of `==` when filtering on a vector > length 1.

so `filter(Tissue %in% Tissue_type)` would yield the correct result.

This is because of something called *recycling*. You can google it for more info. But basically, when you write `filter(Tissue == Tissue_type)`, you are comparing two vectors of different lengths. 

So say `Tissue` is `c('A', 'A', 'B', 'B', 'C')`, and `Tissue_type` is `c('A', 'B')`. What is happening under the hood is:

|Tissue| Comparison| Tissue_type| Output|
|---|---|---|---|
|'A'|==|'A'|TRUE| 
|'A'|==|'B'|FALSE| 
|'B'|==|'A'|FALSE| 
|'B'|==|'B'|TRUE| 
|'C'|==|'A'|FALSE| 

This is what `filter(Tissue %in% Tissue_type)` does:

|Tissue| Comparison| Tissue_type| Output|
|---|---|---|---|
|'A'|%in%|c('A', 'B')|TRUE| 
|'A'|%in%|c('A', 'B')|TRUE| 
|'B'|%in%|c('A', 'B')|TRUE| 
|'B'|%in%|c('A', 'B')|TRUE| 
|'C'|%in%|c('A', 'B')|FALSE|

**Comment by Yifan-Yin** [comment]
Great! Thanks for your explanation!

**Comment by Yifan-Yin** [comment]
An option (checkbox) has been added to allow users to select which cell types to plot. The plot will be automatically updated when users change the selections in the checkbox.

Here is an example.

![image](https://user-images.githubusercontent.com/52260541/70983003-e0e6cb80-206c-11ea-813b-a86eda6c2c97.png)
![image](https://user-images.githubusercontent.com/52260541/70983244-40dd7200-206d-11ea-911d-7ce290fcacb3.png)

**Comment by wvictor14** [comment]
It looks great, thanks!
